#model_name: "deepseek/DeepSeek-V3-0324" mistral-ai/Codestral-2501 openai/gpt-5
model_name: "gpt-4o"
instructions_path: "Tesi/config/system_instructions2.txt"
refined_graph_path: "data/raw/Graph/graph_v2.json"
ground_truth_path: "Tesi/Few_shot_data/responses_query_nl.yaml"
template_query_path: "Tesi/Few_shot_data/query_nl.yaml"
report_output_path: "output/experiment_results.json"